"""Gold metric tests against real KHC data, oracled by hand and human-confirmed (AGENTS.md
milestone 3 log) -- not generated by any production code path. FY2018, the goodwill-impairment
year, computed from the raw silver.company_year values by plain arithmetic:

    current_ratio    = current_assets / current_liabilities  = 9075 / 7503
    quick_ratio       = (current_assets - inventory) / current_liabilities
    working_capital   = current_assets - current_liabilities
    debt_to_equity    = total_liabilities / equity            = 51683 / 51657
    goodwill_to_assets= goodwill / total_assets                = 36503 / 103461
    equity_ex_goodwill= equity - goodwill
    dso               = avg(receivables_2017, receivables_2018) / revenue_2018 * 365
    net_margin        = net_income / revenue                   = -10192 / 26268
    normalized_net_income = net_income + goodwill_impairment
    net_debt          = (short_term_debt + long_term_debt) - cash

Requires `make ingest && make build` to have populated data/warehouse.duckdb first -- these are
gold-layer integration tests, not unit tests of extraction logic (that's tests/test_normalize.py).
"""

from pathlib import Path

import duckdb
import pytest

WAREHOUSE = Path(__file__).parent.parent / "data" / "warehouse.duckdb"

pytestmark = pytest.mark.skipif(
    not WAREHOUSE.exists(),
    reason="data/warehouse.duckdb not built; run `make ingest && make build` first",
)


def _fy2018_row() -> dict[str, object]:
    con = duckdb.connect(str(WAREHOUSE), read_only=True)
    try:
        schema = con.execute(
            "SELECT table_schema FROM information_schema.tables "
            "WHERE table_name = 'fct_company_year_metrics'"
        ).fetchone()[0]
        cols = [
            "current_ratio",
            "quick_ratio",
            "working_capital",
            "debt_to_equity",
            "goodwill_to_assets",
            "equity_ex_goodwill",
            "dso",
            "net_margin",
            "normalized_net_income",
            "net_debt",
            "null_metric_flags",
        ]
        row = con.execute(
            f"SELECT {','.join(cols)} FROM {schema}.fct_company_year_metrics "
            "WHERE cik = '0001637459' AND fiscal_year = 2018"
        ).fetchone()
    finally:
        con.close()
    assert row is not None, "FY2018 KHC row not found; is the warehouse built for KHC?"
    return dict(zip(cols, row, strict=True))


def test_fy2018_liquidity_matches_oracle() -> None:
    row = _fy2018_row()
    assert row["current_ratio"] == pytest.approx(1.2095, abs=1e-3)
    assert row["quick_ratio"] == pytest.approx(0.8541, abs=1e-3)
    assert row["working_capital"] == pytest.approx(1_572_000_000.0)


def test_fy2018_solvency_matches_oracle() -> None:
    row = _fy2018_row()
    assert row["debt_to_equity"] == pytest.approx(1.0005, abs=1e-3)
    assert row["net_debt"] == pytest.approx(29_661_000_000.0)


def test_fy2018_goodwill_story_matches_oracle() -> None:
    """The flagship KHC finding: goodwill-heavy, equity survives ex-goodwill but barely."""
    row = _fy2018_row()
    assert row["goodwill_to_assets"] == pytest.approx(0.3528, abs=1e-3)
    assert row["equity_ex_goodwill"] == pytest.approx(15_154_000_000.0)
    assert row["equity_ex_goodwill"] > 0  # not wiped out, but goodwill is ~35% of assets


def test_fy2018_dso_matches_oracle() -> None:
    row = _fy2018_row()
    assert row["dso"] == pytest.approx(21.19, abs=0.05)


def test_fy2018_profitability_matches_oracle() -> None:
    row = _fy2018_row()
    assert row["net_margin"] == pytest.approx(-0.3880, abs=1e-3)
    # Still a loss even excluding the goodwill impairment -- a real, non-obvious finding.
    assert row["normalized_net_income"] == pytest.approx(-3_184_000_000.0)
    assert row["normalized_net_income"] < 0


def test_fy2018_has_no_divide_by_zero_flags() -> None:
    assert _fy2018_row()["null_metric_flags"] == []
